version: '3.8'

services:
  # 主应用 - 使用优化的 Dockerfile
  app:
    build:
      context: .
      dockerfile: Dockerfile.fast  # 使用优化版
    container_name: court-argument
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - DEBUG=true
      - LOG_LEVEL=INFO
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-CourtSim2024!}
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - qdrant
      - neo4j
      - redis
    networks:
      - court-sim-network
    restart: unless-stopped

  # Qdrant 向量数据库
  qdrant:
    image: qdrant/qdrant:latest
    container_name: court-sim-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - court-sim-network
    restart: unless-stopped

  # Neo4j 图数据库
  neo4j:
    image: neo4j:5-community
    container_name: court-sim-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-CourtSim2024!}
      - NEO4J_dbms_memory_pagecache_size=512M  # 减少内存使用
      - NEO4J_dbms_memory_heap_max__size=512M
    networks:
      - court-sim-network
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: court-sim-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - court-sim-network
    restart: unless-stopped

networks:
  court-sim-network:
    driver: bridge

volumes:
  qdrant_data:
  neo4j_data:
  redis_data: